# Use the latest R version
FROM rocker/r-ver:latest

# Copy the plumber.R script into the Docker image
COPY /R/plumber.R /plumber.R

# Install the plumber package
RUN R -e "install.packages('plumber')"

# Expose the port your API will run on
EXPOSE 8000

# Specify the command to run your API
CMD ["R", "-e", "pr <- plumber::plumb('/plumber.R'); pr$run(port=8000)"]
