servers:
  - url: ''
openapi: 3.0.3
info:
  title: Penguin Predictions API
  description: Penguin API
  version: 1.0.0
paths:
  /health-check:
    get:
      summary: 'Determine if the API is running and listening as expected'
      responses:
        default:
          description: Default response.
      parameters: []
  /predict:
    get:
      summary: 'Predict penguin species based on input data'
      responses:
        default:
          description: Default response.
      parameters:
        - name: bill_length_mm
          in: query
          description: Penguin bill length
          required: true
          schema:
            type: number
            example: 46.8
        - name: bill_depth_mm
          in: query
          description: Penguin bill depth
          required: true
          schema:
            type: number
            example: 16.1
        - name: flipper_length_mm
          in: query
          description: Penguin flipper length
          required: true
          schema:
            type: number
            example: 150
        - name: body_mass_g
          in: query
          description: Penguin body mass
          required: true
          schema:
            type: number
            example: 5500
